name: ✨ Feature Request
description: Suggest an idea or improvement for the project
title: "[FEATURE] Component - What should be added - Why or when"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please take a moment to provide detailed information below.

  - type: input
    id: environment
    attributes:
      label: 📋 Environment (optional)
      description: If this feature is platform-specific, mention it here (OS, Unity version, etc.)
      placeholder: "Windows 10, Unity 2022.3.5f1"

  - type: textarea
    id: description
    attributes:
      label: 📝 Feature Description
      description: What would you like to see added or changed?
      placeholder: Describe the idea clearly, including context and intended usage.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 🚀 Motivation and Rationale
      description: Why is this feature important or useful? What problem does it solve?
      placeholder: Explain the value or purpose of the feature.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Suggested Solution (optional)
      description: If you have a specific implementation idea, describe it here.
      placeholder: Describe how you imagine this could be implemented.

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives or workarounds
      description: Have you considered other ways to achieve the same result?
      placeholder: Mention any existing solutions or compromises you've tried.

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional Context or References
      description: Add any relevant links, sketches, screenshots, or examples.
      placeholder: Include images, similar feature references, or design notes if relevant.
